name: Deploy to AWS Lambda

on:
  push:
    branches:
      - nazar-nogpu-lambda 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install zappa

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1 

    - name: Set Environment Variables
      run: |
        jq '.main.environment_variables |= . + {
        "FIREBASE_API_KEY": "${{ secrets.FIREBASE_API_KEY }}",
        "FIREBASE_AUTH_DOMAIN": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
        "FIREBASE_DATABASE_URL": "${{ secrets.FIREBASE_DATABASE_URL }}",
        "FIREBASE_PROJECT_ID": "${{ secrets.FIREBASE_PROJECT_ID }}",
        "FIREBASE_STORAGE_BUCKET": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
        "FIREBASE_MESSAGING_SENDER_ID": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
        "FIREBASE_APP_ID": "${{ secrets.FIREBASE_APP_ID }}",
        "MAILER_SENDER_API_KEY": "${{ secrets.MAILER_SENDER_API_KEY }}"
        }' zappa_settings.json > zappa_settings_temp.json && mv zappa_settings_temp.json zappa_settings.json

    - name: Deploy to Lambda
      run: |
        zappa update main || zappa deploy main